### ISSUE TITLE
A simple Metrics function to display key metrics like R2, Adjusted R2, AIC and BIC

### ISSUE THREAD

**Issue by sultanaltair96** [mauricio1986/gmnl#1]
model.metrics.gmnl = function (model) {
  
  q <- nrow(getElement(model, 'residuals'))
  
  ll1 <- model$logLik$maximum[1]
  ll0 = log(0.3333333333333) * q
  
  r2 = 1 - (ll1 / ll0)
  adj_r2 = (1 - (ll1 - (length(model$coefficients)))/(ll0) )
  aic = AIC(model)
  bic = BIC(model)
  
  result_list = list( "R2" = round(r2, digits = 3) , "AdjustedR2" = round(adj_r2,digits = 4),  "AIC" = aic, "BIC" = bic)
  
  return(result_list)
  
}

**Comment by mauricio1986** [comment]
Many Thanks!

I will check and add this function in the next release of gmnl. 

Best, 

Mauricio
